export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED',
  INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',

  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  EMPLOYEE_CODE_ALREADY_EXISTS = 'EMPLOYEE_CODE_ALREADY_EXISTS',
  EMPLOYEE_NOT_FOUND = 'EMPLOYEE_NOT_FOUND',
  CANNOT_DELETE_ADMIN = 'CANNOT_DELETE_ADMIN',

  ATTENDANCE_ALREADY_CLOCKED_IN = 'ATTENDANCE_ALREADY_CLOCKED_IN',
  ATTENDANCE_NOT_CLOCKED_IN = 'ATTENDANCE_NOT_CLOCKED_IN',
  ATTENDANCE_ALREADY_CLOCKED_OUT = 'ATTENDANCE_ALREADY_CLOCKED_OUT',
  ATTENDANCE_RECORD_NOT_FOUND = 'ATTENDANCE_RECORD_NOT_FOUND',

  LEAVE_INVALID_DATE_RANGE = 'LEAVE_INVALID_DATE_RANGE',
  LEAVE_OVERLAP = 'LEAVE_OVERLAP',
  LEAVE_NOT_FOUND = 'LEAVE_NOT_FOUND',
  LEAVE_ALREADY_PROCESSED = 'LEAVE_ALREADY_PROCESSED',
  LEAVE_REJECTION_REASON_REQUIRED = 'LEAVE_REJECTION_REASON_REQUIRED',
}
